// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StayFlex2.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250204093111_FixPrimaryKey")]
    partial class FixPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StayFlex2.Model.Bewertung", b =>
                {
                    b.Property<int>("BewertungsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BewertungsID"));

                    b.Property<int>("GastID")
                        .HasColumnType("int");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("SterneBewertung")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BewertungsID");

                    b.HasIndex("GastID");

                    b.HasIndex("HotelID");

                    b.ToTable("Bewertungen");
                });

            modelBuilder.Entity("StayFlex2.Model.Buchung", b =>
                {
                    b.Property<int>("BuchungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BuchungID"));

                    b.Property<DateTime>("Buchungsdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GastID")
                        .HasColumnType("int");

                    b.Property<double>("Kosten")
                        .HasColumnType("double");

                    b.Property<int>("ZimmerID")
                        .HasColumnType("int");

                    b.HasKey("BuchungID");

                    b.HasIndex("GastID");

                    b.HasIndex("ZimmerID");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("StayFlex2.Model.Gast", b =>
                {
                    b.Property<int>("GastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GastID"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Geburtsdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Stammgast")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GastID");

                    b.ToTable("Gaeste");
                });

            modelBuilder.Entity("StayFlex2.Model.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HotelID"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stadt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sterne")
                        .HasColumnType("int");

                    b.HasKey("HotelID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("StayFlex2.Model.Rechnung", b =>
                {
                    b.Property<int>("RechnungsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RechnungsID"));

                    b.Property<double>("Betrag")
                        .HasColumnType("double");

                    b.Property<int>("BuchungID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Erstellungsdatum")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RechnungsID");

                    b.HasIndex("BuchungID")
                        .IsUnique();

                    b.ToTable("Rechnungen");
                });

            modelBuilder.Entity("StayFlex2.Model.Zimmer", b =>
                {
                    b.Property<int>("ZimmerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZimmerID"));

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preis")
                        .HasColumnType("double");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Verfuegbarkeit")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ZimmerID");

                    b.HasIndex("HotelID");

                    b.ToTable("Zimmer");
                });

            modelBuilder.Entity("StayFlex2.Model.Bewertung", b =>
                {
                    b.HasOne("StayFlex2.Model.Gast", "Gast")
                        .WithMany()
                        .HasForeignKey("GastID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayFlex2.Model.Hotel", "Hotel")
                        .WithMany("Bewertungen")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gast");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("StayFlex2.Model.Buchung", b =>
                {
                    b.HasOne("StayFlex2.Model.Gast", "Gast")
                        .WithMany("Buchungen")
                        .HasForeignKey("GastID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayFlex2.Model.Zimmer", "Zimmer")
                        .WithMany()
                        .HasForeignKey("ZimmerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gast");

                    b.Navigation("Zimmer");
                });

            modelBuilder.Entity("StayFlex2.Model.Rechnung", b =>
                {
                    b.HasOne("StayFlex2.Model.Buchung", "Buchung")
                        .WithOne("Rechnung")
                        .HasForeignKey("StayFlex2.Model.Rechnung", "BuchungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buchung");
                });

            modelBuilder.Entity("StayFlex2.Model.Zimmer", b =>
                {
                    b.HasOne("StayFlex2.Model.Hotel", "Hotel")
                        .WithMany("Zimmer")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("StayFlex2.Model.Buchung", b =>
                {
                    b.Navigation("Rechnung")
                        .IsRequired();
                });

            modelBuilder.Entity("StayFlex2.Model.Gast", b =>
                {
                    b.Navigation("Buchungen");
                });

            modelBuilder.Entity("StayFlex2.Model.Hotel", b =>
                {
                    b.Navigation("Bewertungen");

                    b.Navigation("Zimmer");
                });
#pragma warning restore 612, 618
        }
    }
}
